source 'https://rubygems.org'

gem 'rails', '~> 4.1'
gem 'mysql2'

group :development, :test do
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'thin'
end

gem 'jquery-rails'
gem 'capistrano'
gem 'capistrano_colors'
gem 'capistrano-ext'
gem 'rvm-capistrano'
gem 'haml'
gem 'haml-rails'
gem 'rmagick', '2.13.2'
gem 'coffee-rails'
gem 'therubyracer'
gem 'uglifier', '>= 1.0.3'
gem 'activeadmin', github: 'activeadmin'
gem 'sass'
gem 'sass-rails', '5.0.0.beta1'
gem 'meta_search'
gem 'kaminari'
gem 'acts_as_permalink'
gem 'rdiscount'
gem 'carrierwave'
